### ISSUE TITLE
想请问你们是如何消除空洞的

### ISSUE THREAD

**Issue by upupbo** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#1]
想请问你们是如何消除空洞的

**Comment by hs0531** [comment]
现在有两个思路：
1.就是你们采用的那种硬阈值
2.可以参照Lmoer在参加天池的比赛时的思路，代码在github上搜Lmoer就可以搜到他的github
顺带问一下你们当时的代码里网络的解码部分没有融合编码部分的底层特征是出于什么考虑呢？







---原始邮件---
发件人: "upupbo"<notifications@github.com&gt;
发送时间: 2020年3月15日(周日) 中午12:50
收件人: "lin-honghui/tianchi_CountyAgriculturalBrain_top1"<tianchi_CountyAgriculturalBrain_top1@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lin-honghui/tianchi_CountyAgriculturalBrain_top1] 想请问你们是如何消除空洞的 (#1)




 
想请问你们是如何消除空洞的

**Comment by lin-honghui** [comment]
1、消除孔洞部分直接用的阈值处理，阈值参数的选取根据A榜数据调优。代码参考在utils/remove_small_object.py
2、关于没有融入编码部分底层特征：比较早的时候尝试过，但网络预测结果会变得“零碎”（可能是我加入底层特征通道数太多），后来砍掉底层之后，网络变快了，预测也变得更加平滑。我想加入底层特征可能对比较细致的预测会有帮助，但对这次题目遥感数据这种大面积的预测，直接用高层特征上采样也有很好的预测结果。
