### ISSUE TITLE
请问一下有人遇到分割结果有明显锯齿状吗？

### ISSUE THREAD

**Issue by qingchengboy** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#10]
感谢楼主分享代码，谢谢。我在训练自己数据过程中，发现小图片分割结果的边缘明显的锯齿状，有遇到过这种情况吗。训练与预测都是512×512。

**Comment by lin-honghui** [comment]
锯齿原因可能是上采样做的比较粗糙，这份代码是针对遥感分割场景，特点是大面积预测，上采样我处理的很简单，decoder两次4倍上采样直接输出，所以会有边缘锯齿，可以试试把decoder上采样做精细一些





------------------ 原始邮件 ------------------
发件人: lzq ***@***.***&gt;
发送时间: 2021年7月19日 11:34
收件人: lin-honghui/tianchi_CountyAgriculturalBrain_top1 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[lin-honghui/tianchi_CountyAgriculturalBrain_top1] 请问一下有人遇到分割结果有明显锯齿状吗？ (#10)





 
感谢楼主分享代码，谢谢。我在训练自己数据过程中，发现小图片分割结果的边缘明显的锯齿状，有遇到过这种情况吗。训练与预测都是512×512。

**Comment by qingchengboy** [comment]
@lin-honghui 明白了，谢谢楼主，我自己修改一下。
