### ISSUE TITLE
前辈 可以问下你还有数据集吗 可以分享下吗

### ISSUE THREAD

**Issue by sakarion** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#3]

**Comment by lin-honghui** [comment]
邮箱我一下吧，lin.honghui@qq.com，我发给你

**Comment by sakarion** [comment]
15829849851@163.com， 谢谢前辈~感谢您的回复和分享！

**Comment by sakarion** [comment]
15829849851@163.com，谢谢前辈〜感谢您的回复和分享！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lin-honghui/tianchi_CountyAgriculturalBrain_top1"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 中午1:07
收件人:&nbsp;"lin-honghui/tianchi_CountyAgriculturalBrain_top1"<tianchi_CountyAgriculturalBrain_top1@noreply.github.com&gt;;
抄送:&nbsp;"言小乔"<1043220891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lin-honghui/tianchi_CountyAgriculturalBrain_top1] 前辈 可以问下你还有数据集吗 可以分享下吗 (#3)





 
邮箱我一下吧，lin.honghui@qq.com，我发给你
