### ISSUE TITLE
请问 你训练测试loss miou指标达到了多少?

### ISSUE THREAD

**Issue by elesun2018** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#5]
请问 你训练测试loss miou指标达到了多少?
我按照你的readme train loss 0.2左右，

谢谢

**Comment by lin-honghui** [comment]
抱歉哈，时间有点久了实验细节不大记得。配置文件里的epoch可以再改大一些，我提交时候一般是取epoch 60 70 80 出来做一个snapshot ensemble
