### ISSUE TITLE
inference error   ValueError: could not broadcast input array from shape (512,512) into shape (512,256)

### ISSUE THREAD

**Issue by elesun2018** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#6]
请问inference代码，下面有个报错
ValueError: could not broadcast input array from shape (512,512) into shape (512,256)

if(buttomright_x-topleft_x)==1024 and (buttomright_y-topleft_y)==1024:
        print("predict_png.shape",predict_png.shape) # predict_png.shape (43520, 22016)
        print(topleft_x,topleft_y,buttomright_x,buttomright_y)
        # 每次预测只保留图像中心(512,512)区域预测结果
        # if predict_png[topleft_y+256:buttomright_y-256,topleft_x+256:buttomright_x-256].shape !=  (512,512):
        #     print(predict_png[topleft_y+256:buttomright_y-256,topleft_x+256:buttomright_x-256].shape) # ,21760:22272
        predict_png[topleft_y+256:buttomright_y-256,topleft_x+256:buttomright_x-256] = predict[256:768,256:768]
应该如何修改才好，谢谢

**Comment by lin-honghui** [comment]
加下我qq 694559700 讨论吧
