### ISSUE TITLE
关于config/.py里数据制作制作流程

### ISSUE THREAD

**Issue by nanhui69** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#8]
请问该项目里的数据制作流程是怎样的，比如deeplabv3plus_resnet101_StepLR_Adam.py里 ：
dataset=dict(type="PNG_Dataset",
                     csv_file=r'/home/LinHonghui/Datasets/tianchi_CountyAgricultural/Crop1024/train.csv',
                     image_dir=r'/home/LinHonghui/Datasets/tianchi_CountyAgricultural/Crop1024/image/',
                     mask_dir=r'/home/LinHonghui/Datasets/tianchi_CountyAgricultural/Crop1024/label/'),
上面对应的几个，然后训练时需要另外下载预训练模型么？ @lin-honghui

**Comment by lin-honghui** [comment]
你好，数据预处理流程请参考 prepare.sh （预处理主要是把PNG大图切成小图，方便训练和推理）。

**Comment by nanhui69** [comment]
> 你好，数据预处理流程请参考 prepare.sh （预处理主要是把PNG大图切成小图，方便训练和推理）。

我试试看，这么大的图处理起来估计要好久啊

**Comment by nanhui69** [comment]
发现内存不够用，如果按照data_prepare.py 脚本里提示的gdal方法 电脑需要多大的内存呢，有使用gdal脚本可以参考么？ @lin-honghui

**Comment by lin-honghui** [comment]
> 发现内存不够用，如果按照data_prepare.py 脚本里提示的gdal方法 电脑需要多大的内存呢，有使用gdal脚本可以参考么？ @lin-honghui

gdal api 比较简单，建议测试一下

**Comment by nanhui69** [comment]
> > 发现内存不够用，如果按照data_prepare.py 脚本里提示的gdal方法 电脑需要多大的内存呢，有使用gdal脚本可以参考么？ @lin-honghui
> 
> gdal api 比较简单，建议测试一下

ubuntu系统下有适配的gdal版本么？

**Comment by nanhui69** [comment]
> > 发现内存不够用，如果按照data_prepare.py 脚本里提示的gdal方法 电脑需要多大的内存呢，有使用gdal脚本可以参考么？ @lin-honghui
> 
> gdal api 比较简单，建议测试一下

这个data_prepare处理脚本在处理 image_21.png时会出错啊

**Comment by nanhui69** [comment]
请问有处理好的数据分享下么？ @lin-honghui
