### ISSUE TITLE
How to choose the value alpha in Label Smoothing loss function?

### ISSUE THREAD

**Issue by myknowntime** [lin-honghui/tianchi_CountyAgriculturalBrain_top1#9]
Appreciate your work.
    
     I know that the hard examples are optimized as label smoothing loss function, 
and the ground-truth label k distribution is replaced as q(k)=(1-alpha)+alpha/K. I noticed that the value of alpha in your code is chosen as the percentage of hard examples, but why set a upper limit 0.2? 
    In addition, I still have a basic problem, you used a 11*11 conv2d to compute the edge mask, is the conv2d called Laplacian operator, can you explain how it works(it would be better if you could provide related articles of the explanation). 
    Wait for your reply sincerely.

**Comment by lin-honghui** [comment]
2019 天池县域农业大脑AI挑战赛_冠军_方案分享 - now more的文章 - 知乎
https://zhuanlan.zhihu.com/p/166435221
